import React from "react";

export const About = () => {
    return <div>
        <h2>About Page</h2>
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
        <ntext>Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ab sunt aliquam suscipit dolor inventore laborum doloribus, aliquid consequuntur laudantium nam ipsa voluptates porro ad est incidunt impedit esse corrupti, necessitatibus accusantium. Qui quam sed beatae dignissimos enim officiis nam, voluptates molestias esse cumque magni similique nobis a magnam perferendis perspiciatis? Eligendi corrupti quod laboriosam maxime velit consequatur, veritatis similique voluptates, dolorem alias impedit ducimus commodi error! Voluptatem fuga adipisci at, nostrum quo rem, quibusdam beatae laborum magni, eaque recusandae? Cumque neque ullam hic, vitae iure nulla similique unde eaque cum omnis? Rerum perferendis culpa tempore, saepe officia mollitia sed!</ntext>
        <br />
    </div>
}